# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notifications' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Notifications
  pod 'SimulatorRemoteNotifications', '~> 0.0.3'

  target 'NotificationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotificationsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
